name: Build Clash Verge Rev

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create sidecar directory
        run: mkdir src-tauri\sidecar

      - name: Download Mihomo core
        run: |
          curl -L --retry 5 --retry-delay 5 https://github.com/MetaCubeX/mihomo/releases/download/v1.18.3/mihomo-windows-amd64.exe -o src-tauri\sidecar\verge-mihomo-x86_64-pc-windows-msvc.exe

      - name: Verify file
        run: dir src-tauri\sidecar

      - name: Build application
        run: pnpm tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clash-verge-build
          path: src-tauri/target/release/bundle

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build-${{ github.run_number }}
          files: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi
