name: Build Clash Verge Rev

on:
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download Mihomo core
        shell: powershell
        run: |
          mkdir src-tauri\sidecar
          Invoke-WebRequest `
          -Uri https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-windows-amd64.exe `
          -OutFile src-tauri\sidecar\verge-mihomo-x86_64-pc-windows-msvc.exe

      - name: Build application
        run: pnpm tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clash-verge-build
          path: src-tauri/target/release/bundle

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build-${{ github.run_number }}
          files: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi
